version: '3'

services:
    apache:
        build: .docker/apache
        container_name: symfony_apache
        ports:
          - "8000:80"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./app:/home/wwwroot/app
        depends_on:
          - php

    mysql:
        image: mysql
        ports:
          - "3307:3306"
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: symfony_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
          - ./.data/mysql:/var/lib/mysql
    mysql_test:
      image: mysql
      ports:
        - "3308:3306"
      command: "--default-authentication-plugin=mysql_native_password"
      container_name: symfony_mysql_test
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony_test
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      volumes:
        - ./.data/mysql_test:/var/lib/mysql

    php:
        build: .docker/php
        container_name: symfony_php
        working_dir: /home/wwwroot/app
        volumes:
          - ./app:/home/wwwroot/app
        environment:
          - maildev_host=symfony_maildev
        depends_on:
          - maildev
          - mysql
          - mysql_test

    maildev:
        image: djfarrelly/maildev
        container_name: symfony_maildev
        ports:
          - "8001:80"